workflows:
  android-ios-workflow:
    name: Android iOS Workflow
    triggering:
      events:                       # List the events that trigger builds
        - push
        - pull_request
        - pull_request_labeled      #GitHub only
        - tag
      branch_patterns:              # Include or exclude watched branches
        - pattern: 'main'
          include: true
          source: true
      cancel_previous_builds: true  # Set to `true` to automatically cancel outdated webhook builds
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "com.dicoding.ditonton"
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Android build
        script: |
          flutter build appbundle --debug
      - name: Flutter unit tests core
        script: |
          cd core && flutter test && cd ..
      - name: Flutter unit tests movie
        script: |
          cd core && flutter test && cd ..
      - name: Flutter unit tests search
        script: |
          cd search && flutter test && cd ..
      - name: Flutter unit tests tvs
        script: |
          cd tvs && flutter test && cd ..
        ignore_failure: true