workflows:
  android-ios-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "com.dicoding.ditonton" # <-- Put your package name here
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Android build
        script: |
          flutter build appbundle --debug
      - name: ios Build
        script: |
          flutter build ios --debug --no-codesign
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true